# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Modelo(object):
    def setupUi(self, Modelo):
        if not Modelo.objectName():
            Modelo.setObjectName(u"Modelo")
        Modelo.resize(989, 710)
        Modelo.setMinimumSize(QSize(989, 710))
        Modelo.setMaximumSize(QSize(989, 710))
        Modelo.setStyleSheet(u"body {background-color: rgb(0, 0, 0);}")
        self.Title = QLabel(Modelo)
        self.Title.setObjectName(u"Title")
        self.Title.setGeometry(QRect(10, 0, 941, 91))
        self.EmployeeNumber = QLabel(Modelo)
        self.EmployeeNumber.setObjectName(u"EmployeeNumber")
        self.EmployeeNumber.setGeometry(QRect(30, 155, 201, 31))
        self.MonthShift = QLabel(Modelo)
        self.MonthShift.setObjectName(u"MonthShift")
        self.MonthShift.setGeometry(QRect(0, 220, 201, 31))
        self.Req1 = QLabel(Modelo)
        self.Req1.setObjectName(u"Req1")
        self.Req1.setGeometry(QRect(30, 270, 251, 91))
        self.Req2 = QLabel(Modelo)
        self.Req2.setObjectName(u"Req2")
        self.Req2.setGeometry(QRect(30, 365, 331, 91))
        self.Req3 = QLabel(Modelo)
        self.Req3.setObjectName(u"Req3")
        self.Req3.setGeometry(QRect(30, 460, 341, 91))
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Req3.sizePolicy().hasHeightForWidth())
        self.Req3.setSizePolicy(sizePolicy)
        self.Req3.setTabletTracking(False)
        self.Req4 = QLabel(Modelo)
        self.Req4.setObjectName(u"Req4")
        self.Req4.setGeometry(QRect(30, 555, 341, 91))
        self.InputButton = QPushButton(Modelo)
        self.InputButton.setObjectName(u"InputButton")
        self.InputButton.setGeometry(QRect(380, 310, 221, 121))
        font = QFont()
        font.setFamily(u"Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.InputButton.setFont(font)
        self.InputButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.InputButton.setContextMenuPolicy(Qt.NoContextMenu)
        self.InputButton.setAutoRepeat(False)
        self.Description = QLabel(Modelo)
        self.Description.setObjectName(u"Description")
        self.Description.setGeometry(QRect(30, 50, 891, 61))
        font1 = QFont()
        font1.setFamily(u"Arial")
        font1.setPointSize(11)
        self.Description.setFont(font1)
        self.EmployeeNumberInput = QDoubleSpinBox(Modelo)
        self.EmployeeNumberInput.setObjectName(u"EmployeeNumberInput")
        self.EmployeeNumberInput.setGeometry(QRect(40, 185, 111, 22))
        self.EmployeeNumberInput.setMaximum(1000000000.000000000000000)
        self.MonthShiftInput = QDoubleSpinBox(Modelo)
        self.MonthShiftInput.setObjectName(u"MonthShiftInput")
        self.MonthShiftInput.setGeometry(QRect(40, 250, 111, 22))
        self.MonthShiftInput.setMaximum(1000000000.000000000000000)
        self.Req1Input = QDoubleSpinBox(Modelo)
        self.Req1Input.setObjectName(u"Req1Input")
        self.Req1Input.setGeometry(QRect(40, 345, 111, 22))
        self.Req1Input.setMaximum(1000000000.000000000000000)
        self.Req2Input = QDoubleSpinBox(Modelo)
        self.Req2Input.setObjectName(u"Req2Input")
        self.Req2Input.setGeometry(QRect(40, 440, 111, 22))
        self.Req2Input.setMaximum(1000000000.000000000000000)
        self.Req3Input = QDoubleSpinBox(Modelo)
        self.Req3Input.setObjectName(u"Req3Input")
        self.Req3Input.setGeometry(QRect(40, 535, 111, 22))
        self.Req3Input.setMaximum(1000000000.000000000000000)
        self.Req4Input = QDoubleSpinBox(Modelo)
        self.Req4Input.setObjectName(u"Req4Input")
        self.Req4Input.setGeometry(QRect(40, 630, 111, 22))
        self.Req4Input.setMaximum(1000000000.000000000000000)
        self.TextoRespuesta = QLabel(Modelo)
        self.TextoRespuesta.setObjectName(u"TextoRespuesta")
        self.TextoRespuesta.setGeometry(QRect(620, 270, 351, 91))
        self.TextoRespuesta.setMaximumSize(QSize(351, 91))
        font2 = QFont()
        font2.setFamily(u"Arial")
        font2.setBold(True)
        font2.setWeight(75)
        self.TextoRespuesta.setFont(font2)
        self.TextoRespuesta.setTabletTracking(False)
        self.TextoRespuesta.setWordWrap(True)
        self.Model = QLabel(Modelo)
        self.Model.setObjectName(u"Model")
        self.Model.setGeometry(QRect(640, 370, 311, 61))
        self.Model.setMaximumSize(QSize(311, 61))
        font3 = QFont()
        font3.setFamily(u"Arial")
        font3.setPointSize(11)
        font3.setBold(False)
        font3.setWeight(50)
        self.Model.setFont(font3)
        self.Model.setWordWrap(True)
        self.frameInput = QFrame(Modelo)
        self.frameInput.setObjectName(u"frameInput")
        self.frameInput.setGeometry(QRect(10, 110, 351, 571))
        self.frameInput.setAutoFillBackground(False)
        self.frameInput.setStyleSheet(u"")
        self.frameInput.setFrameShape(QFrame.StyledPanel)
        self.frameInput.setFrameShadow(QFrame.Raised)
        self.TitleInput = QLabel(self.frameInput)
        self.TitleInput.setObjectName(u"TitleInput")
        self.TitleInput.setGeometry(QRect(0, 0, 351, 51))
        self.frameOutput = QFrame(Modelo)
        self.frameOutput.setObjectName(u"frameOutput")
        self.frameOutput.setGeometry(QRect(620, 110, 351, 571))
        self.frameOutput.setFrameShape(QFrame.StyledPanel)
        self.frameOutput.setFrameShadow(QFrame.Raised)
        self.TitleInput_3 = QLabel(self.frameOutput)
        self.TitleInput_3.setObjectName(u"TitleInput_3")
        self.TitleInput_3.setGeometry(QRect(0, 0, 351, 61))
        self.frameModelo = QFrame(Modelo)
        self.frameModelo.setObjectName(u"frameModelo")
        self.frameModelo.setGeometry(QRect(630, 360, 331, 91))
        self.frameModelo.setFrameShape(QFrame.StyledPanel)
        self.frameModelo.setFrameShadow(QFrame.Raised)
        self.ErrorEmp = QLabel(Modelo)
        self.ErrorEmp.setObjectName(u"ErrorEmp")
        self.ErrorEmp.setGeometry(QRect(40, 210, 311, 16))
        self.ErrorEq4 = QLabel(Modelo)
        self.ErrorEq4.setObjectName(u"ErrorEq4")
        self.ErrorEq4.setGeometry(QRect(40, 650, 311, 16))
        self.ErrorTur = QLabel(Modelo)
        self.ErrorTur.setObjectName(u"ErrorTur")
        self.ErrorTur.setGeometry(QRect(40, 275, 311, 16))
        self.ErrorEq1 = QLabel(Modelo)
        self.ErrorEq1.setObjectName(u"ErrorEq1")
        self.ErrorEq1.setGeometry(QRect(40, 370, 311, 16))
        self.ErrorEq2 = QLabel(Modelo)
        self.ErrorEq2.setObjectName(u"ErrorEq2")
        self.ErrorEq2.setGeometry(QRect(40, 465, 311, 16))
        self.ErrorEq3 = QLabel(Modelo)
        self.ErrorEq3.setObjectName(u"ErrorEq3")
        self.ErrorEq3.setGeometry(QRect(40, 565, 311, 16))
        self.frameModelo.raise_()
        self.frameOutput.raise_()
        self.frameInput.raise_()
        self.Title.raise_()
        self.EmployeeNumber.raise_()
        self.MonthShift.raise_()
        self.Req1.raise_()
        self.Req2.raise_()
        self.Req3.raise_()
        self.Req4.raise_()
        self.InputButton.raise_()
        self.Description.raise_()
        self.EmployeeNumberInput.raise_()
        self.MonthShiftInput.raise_()
        self.Req1Input.raise_()
        self.Req2Input.raise_()
        self.Req3Input.raise_()
        self.Req4Input.raise_()
        self.TextoRespuesta.raise_()
        self.Model.raise_()
        self.ErrorTur.raise_()
        self.ErrorEq1.raise_()
        self.ErrorEq2.raise_()
        self.ErrorEq3.raise_()

        self.retranslateUi(Modelo)

        QMetaObject.connectSlotsByName(Modelo)
    # setupUi

    def retranslateUi(self, Modelo):
        Modelo.setWindowTitle(QCoreApplication.translate("Modelo", u"Interfaz de Usuario", None))
        self.Title.setText(QCoreApplication.translate("Modelo", u"<html><head/><body><p align=\"center\"><span style=\" font-family:'Arial'; font-size:18pt; font-weight:600;\">Predictor de Modelos Heuristicos para Turnos Laborales</span></p></body></html>", None))
        self.EmployeeNumber.setText(QCoreApplication.translate("Modelo", u"<html><head/><body><p><span style=\" font-family:'Arial'; font-size:10pt; font-weight:600;\">Cantidad Total de Empleados</span></p></body></html>", None))
        self.MonthShift.setText(QCoreApplication.translate("Modelo", u"<html><head/><body><p align=\"center\"><span style=\" font-family:'Arial'; font-size:10pt; font-weight:600;\">Total Turnos Mensuales</span></p></body></html>", None))
        self.Req1.setText(QCoreApplication.translate("Modelo", u"<html><head/><body><p><span style=\" font-family:'Arial'; font-size:10pt; font-weight:600;\">Requerimiento 1:</span></p><p><span style=\" font-family:'Arial'; font-size:10pt; font-weight:600;\">Horas diarias maximas por empleado</span></p></body></html>", None))
        self.Req2.setText(QCoreApplication.translate("Modelo", u"<html><head/><body><p><span style=\" font-family:'Arial'; font-size:10pt; font-weight:600;\">Requerimiento 2:</span></p><p><span style=\" font-family:'Arial'; font-size:10pt; font-weight:600;\">Tiempo [m] de descanso minimo por empleado</span></p></body></html>", None))
        self.Req3.setText(QCoreApplication.translate("Modelo", u"<html><head/><body><p><span style=\" font-family:'Arial'; font-size:10pt; font-weight:600;\">Requerimiento 3:</span></p><p><span style=\" font-family:'Arial'; font-size:10pt; font-weight:600;\">Tiempo [m] de descanso maximo por empleado</span></p></body></html>", None))
        self.Req4.setText(QCoreApplication.translate("Modelo", u"<html><head/><body><p><span style=\" font-family:'Arial'; font-size:10pt; font-weight:600;\">Requerimiento 4:</span></p><p><span style=\" font-family:'Arial'; font-size:10pt; font-weight:600;\">Dias libres al mes</span></p></body></html>", None))
        self.InputButton.setText(QCoreApplication.translate("Modelo", u"PREDECIR MODELO", None))
        self.Description.setText(QCoreApplication.translate("Modelo", u"<html><head/><body><p align=\"center\">\u00a1Bienvenido al predictor de modelos heuristicos para la resoluci\u00f3n de problemas de Turnos Laborales!</p></body></html>", None))
        self.TextoRespuesta.setText(QCoreApplication.translate("Modelo", u"<html><head/><body><p align=\"center\">Para los valores ingresados el Modelo Heuristico que resuelve de mejor manera la distribuci\u00f3n de los Turnos Laborales es</p></body></html>", None))
        self.Model.setText(QCoreApplication.translate("Modelo", u"<html><head/><body><p align=\"center\"></p></body></html>", None))
        self.TitleInput.setText(QCoreApplication.translate("Modelo", u"<html><head/><body><p align=\"center\"><span style=\" font-family:'Arial'; font-size:18pt; font-weight:600;\">Ingreso de Datos</span></p></body></html>", None))
        self.TitleInput_3.setText(QCoreApplication.translate("Modelo", u"<html><head/><body><p align=\"center\"><span style=\" font-family:'Arial'; font-size:18pt; font-weight:600;\">Predicci\u00f3n</span></p></body></html>", None))
        self.ErrorEmp.setText(QCoreApplication.translate("Modelo", u"<html><head/><body><p><span style=\" font-size:7pt; color:#ff0000;\"></span></p></body></html>", None))
        self.ErrorEq4.setText(QCoreApplication.translate("Modelo", u"<html><head/><body><p><span style=\" font-size:7pt; color:#ff0000;\"></span></p></body></html>", None))
        self.ErrorTur.setText(QCoreApplication.translate("Modelo", u"<html><head/><body><p><span style=\" font-size:7pt; color:#ff0000;\"></span></p></body></html>", None))
        self.ErrorEq1.setText(QCoreApplication.translate("Modelo", u"<html><head/><body><p><span style=\" font-size:7pt; color:#ff0000;\"></span></p></body></html>", None))
        self.ErrorEq2.setText(QCoreApplication.translate("Modelo", u"<html><head/><body><p><span style=\" font-size:7pt; color:#ff0000;\"></span></p></body></html>", None))
        self.ErrorEq3.setText(QCoreApplication.translate("Modelo", u"<html><head/><body><p><span style=\" font-size:7pt; color:#ff0000;\"></span></p></body></html>", None))
    # retranslateUi

